-- MySQL Script generated by MySQL Workbench
-- 05/29/19 23:19:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easy_buy
-- -----------------------------------------------------
CREATE SCHEMA `easy_buy`;
USE `easy_buy` ;

-- -----------------------------------------------------
-- Table `easy_buy`.`user`
-- -----------------------------------------------------
CREATE TABLE `easy_buy`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_first_name` VARCHAR(50) NOT NULL,
  `us_last_name` VARCHAR(50) NOT NULL,
  `us_age` INT(2) NOT NULL,
  `us_gender` VARCHAR(6) NULL,
  `us_contact_number` BIGINT(10) NOT NULL,
  `us_user_id` VARCHAR(15) NOT NULL,
  `us_password` VARCHAR(100) NOT NULL,
  `us_status` VARCHAR(1) NOT NULL,
  `us_user_type` VARCHAR(1) NOT NULL,
  `us_secret_ques1` VARCHAR(50) NOT NULL,
  `us_secret_ans1` VARCHAR(50) NOT NULL,
  `us_secret_ques2` VARCHAR(50) NOT NULL,
  `us_secret_ans2` VARCHAR(50) NOT NULL,
  `us_secret_ques3` VARCHAR(50) NOT NULL,
  `us_secret_ans3` VARCHAR(50) NOT NULL,
  `us_reward_points` DECIMAL NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `easy_buy`.`product`
-- -----------------------------------------------------
CREATE TABLE `easy_buy`.`product` (
  `pr_code` INT NOT NULL AUTO_INCREMENT,
  `pr_name` VARCHAR(50) NOT NULL,
  `pr_type` INT(2) NOT NULL,
  `pr_brand` VARCHAR(50) NOT NULL,
  `pr_quatity_type` BIGINT(10) NULL,
  `pr_rate` DECIMAL(15,2) NOT NULL,
  `pr_stock_count` INT(15) NOT NULL,
  `pr_add_date` DATE NOT NULL,
  `pr_aisle` VARCHAR(15) NOT NULL,
  `pr_shelf` VARCHAR(15) NOT NULL,
  `pr_date_of_manufacture` DATE NOT NULL,
  `pr_date_of_expiry` DATE NOT NULL,
  `pr_image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`pr_code`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `easy_buy`.`bill`
-- -----------------------------------------------------
CREATE TABLE `easy_buy`.`bill` (
  `bi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bi_purchase_date` DATE NOT NULL,
  `bi_total_amount` DECIMAL(8,2) NOT NULL,
  `bi_reward_points` INT NOT NULL,
  `bi_us_id` INT(11) NOT NULL,
  `bi_original_amount` DECIMAL(8,2) NOT NULL,
  `bi_final_reward_points` INT NOT NULL,
  PRIMARY KEY (`bi_id`),
  INDEX `fk_bill_user_idx` (`bi_us_id` ASC),
  CONSTRAINT `fk_bill_user`
    FOREIGN KEY (`bi_us_id`)
    REFERENCES `easy_buy`.`user` (`us_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `easy_buy`.`bill_details`
-- -----------------------------------------------------
CREATE TABLE `easy_buy`.`bill_details` (
  `bd_id` INT NOT NULL AUTO_INCREMENT,
  `bd_pr_code` INT NOT NULL,
  `bd_bi_id` INT NOT NULL,
  `bd_pr_quantity` INT NOT NULL,
  PRIMARY KEY (`bd_id`),
  INDEX `bd_pr_fk_idx` (`bd_pr_code` ASC),
  INDEX `bd_bi_fk_idx` (`bd_bi_id` ASC),
  CONSTRAINT `bd_pr_fk`
    FOREIGN KEY (`bd_pr_code`)
    REFERENCES `easy_buy`.`product` (`pr_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bd_bi_fk`
    FOREIGN KEY (`bd_bi_id`)
    REFERENCES `easy_buy`.`bill` (`bi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `easy_buy`.`offer`
-- -----------------------------------------------------
CREATE TABLE `easy_buy`.`offer` (
  `of_id` INT(11) NOT NULL AUTO_INCREMENT,
  `of_date` DATE NOT NULL,
  `of_discount_percentage` INT(11) NOT NULL,
  `of_offer` VARCHAR(100) NOT NULL,
  `of_pr_code` INT(11) NOT NULL,
  PRIMARY KEY (`of_id`),
  
  INDEX `fk_offer_product1_idx` (`of_pr_code` ASC),
  CONSTRAINT `fk_offer_product1`
    FOREIGN KEY (`of_pr_code`)
    REFERENCES `easy_buy`.`product` (`pr_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2;

-- -----------------------------------------------------
-- insert into `easy_buy`.`user`
-- -----------------------------------------------------
INSERT into `easy_buy`.`user` values (1,'super','user',2,'male','1234567890','owner','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','O','O','a','a','a','a','a','a',0);

insert into user
 values('2', 'customer', 'customer', '30', 'Male', '1111111112', 'c1', '$2a$10$iRI4oISXx8APJNlj7i9/JO5oaGtKNztI3cuXOvtSs7jhHOJ/nlSOS', 'U', 'A', 'What is your favorite book', 'Robotics', 'What is your lucky item', 'Cake', 'What is your favorite movie', 'kingkong','0');


insert into user
 values('3', 'shop', 'manager', '30', 'Male', '1111111113', 'a1', '$2a$10$iRI4oISXx8APJNlj7i9/JO5oaGtKNztI3cuXOvtSs7jhHOJ/nlSOS', 'A', 'P', 'What is your favorite book', 'Robotics', 'What is your lucky item', 'Cake', 'What is your favorite movie', 'kingkong','0');

insert into user
 values('4', 'shop', 'manager', '30', 'Male', '1121111113', 'a2', '$2a$10$iRI4oISXx8APJNlj7i9/JO5oaGtKNztI3cuXOvtSs7jhHOJ/nlSOS', 'A', 'A', 'What is your favorite book', 'Robotics', 'What is your lucky item', 'Cake', 'What is your favorite movie', 'kingkong','0');

-- -----------------------------------------------------
-- insert into `easy_buy`.`product`
-- -----------------------------------------------------
INSERT into `easy_buy`.`product` values (1,'Spoon',1,'Milton','1','15','50','2019-03-15','1','1','2017-05-24','2020-4-9','https://images.unsplash.com/photo-1567807951157-76af61943dfe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (2,'Plate',1,'Milton','1','150','50','2019-03-15','1','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1499028203764-8669cfd05719?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (3,'Bottle',1,'Milton','1','50','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1544003484-3cd181d17917?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (4,'Tumbler',1,'Milton','1','70','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1549124785-1c1c62a24388?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (5,'Pressure Cooker',1,'Milton','1','1000','50','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (6,'Garlic Bread',1,'Bakers Fresh','1','70','20','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1573140401552-3fab0b24306f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (7,'Fruit Jam',1,'Bakers Fresh','1','50','30','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1471943311424-646960669fbc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (8,'Cupcakes',1,'Bakers Fresh','1','25','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1465254596705-1ef61f93878c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (9,'Cookies',1,'Bakers Fresh','1','30','50','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1558961363-fa8fdf82db35?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (10,'Homemade chocolate',1,'Bakers Fresh','1','70','10','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1551529674-48920e9b835b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (11,'Orange',1,'Farm Fresh','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1547514701-42782101795e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (12,'Apple',1,'Farm Fresh','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (13,'Potato',1,'Farm Fresh','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (14,'Dragon Fruit',1,'Farm Fresh','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1527325678964-54921661f888?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (15,'Papaya',1,'Farm Fresh','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1526318472351-c75fcf070305?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (16,'Popcorn',1,'ActII','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1572177191856-3cde618dee1f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (17,'Lays',1,'ActII','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1566478989037-eec170784d0b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (18,'Doritos',1,'Doritos','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1567838080002-b388fbd228ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (19,'Nabati',1,'Nabati','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1542843137-144e10cc010b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');
INSERT into `easy_buy`.`product` values (20,'Oreo',1,'Cadbury','1','150','100','2019-03-15','2','1','2017-05-24','2020-04-09','https://images.unsplash.com/photo-1531257243018-c547a2e35767?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60');

-- SELECT * FROM  bill;
-- select * from bill join user on bill.bi_us_id = user.us_id where user.us_user_id = 'aa';
-- drop table bill_details;
-- drop database easy_buy;
-- drop table `easy_buy`.`user`;
-- select * from user;

-- SELECT * FROM bill join bill_details on bill.bi_id = bill_details.bd_bi_id;

-- select * from product;

-- select * from user where us_status='P';
-- select * from user 